crate:
  host: crate.chaos-architect.dev
  images:
    app:
      repository: ghcr.io/psa-department-of-engineering/crate-app
      tag: 1.19.1
    docs:
      repository: ghcr.io/psa-department-of-engineering/crate-docs
      tag: 1.19.1
