apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-docs
  labels:
    app.kubernetes.io/component: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-docs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-docs
        app.kubernetes.io/component: docs
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: docs
          image: "{{ .Values.images.docs.repository }}:{{ .Values.images.docs.tag }}"
          ports:
            - containerPort: 80
