apiVersion: v1
kind: Service
metadata:
  name: crate-docs
  labels:
    app.kubernetes.io/component: docs
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-docs
  ports:
    - port: 80
      targetPort: 80
